package Interfaz;

import static Interfaz.Departamentos.listaDepartamentos;
import static Interfaz.MenúAdmin.Ds;
import Lógica.Municipio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Lógica.Departamento;
import javax.swing.JOptionPane;

public class Municipios extends javax.swing.JFrame {

    //public static Departamentos Ds;
    public static ArrayList<Municipio> listaMunicipios = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    public int filaSeleccionadaMun;
    public static String codDepartamentoLista;

    public Municipios() {
        initComponents();
        model.addColumn("Código Departamento");
        model.addColumn("Nombre Municipio");
        listadeMunicipios.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        códigoDepartamentoMun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreMunicipio = new javax.swing.JTextField();
        regdepartamentos = new javax.swing.JButton();
        agregarMun = new javax.swing.JButton();
        editarMun = new javax.swing.JButton();
        modificarMun = new javax.swing.JButton();
        eliminarMun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadeMunicipios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("MUNICIPIOS");

        jLabel2.setText("Seleccione el departamento a gestionar");

        jLabel3.setText("Código Departamento:");

        jLabel4.setText("Nombre del Municipio:");

        regdepartamentos.setText("Regresar");
        regdepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdepartamentosActionPerformed(evt);
            }
        });

        agregarMun.setText("Agregar");
        agregarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMunActionPerformed(evt);
            }
        });

        editarMun.setText("Editar");
        editarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMunActionPerformed(evt);
            }
        });

        modificarMun.setText("Modificar");
        modificarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMunActionPerformed(evt);
            }
        });

        eliminarMun.setText("Eliminar");
        eliminarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(códigoDepartamentoMun, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarMun, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editarMun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificarMun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarMun, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regdepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(editarMun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificarMun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(códigoDepartamentoMun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarMun)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regdepartamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarMun))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nombreMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );

        listadeMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listadeMunicipios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regdepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdepartamentosActionPerformed
        this.setVisible(false);
        if (Ds == null) {
            Ds = new Departamentos();
        }
        Ds.setVisible(true);
        Ds.setLocationRelativeTo(null);
    }//GEN-LAST:event_regdepartamentosActionPerformed

    private void agregarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMunActionPerformed
        boolean encontrado = false;
        for (int i = 0; i < listaDepartamentos.size(); i++) {
            if (códigoDepartamentoMun.getText().equals(listaDepartamentos.get(i).getCodDpto())) {
                encontrado = true;
                break;
            }
        }
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Este departamento no se encuentra disponble", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (códigoDepartamentoMun.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del Departamento", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (nombreMunicipio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del Municipio", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        Municipio mun = new Municipio(códigoDepartamentoMun.getText(), nombreMunicipio.getText());
        listaMunicipios.add(mun);
        model.addRow(new Object[]{códigoDepartamentoMun.getText(), nombreMunicipio.getText()});
        listadeMunicipios.setModel(model);
        JOptionPane.showMessageDialog(this, "Municipio agregado correctamente", "Proceso Exitoso", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(true);
        códigoDepartamentoMun.setText("");
        nombreMunicipio.setText("");
    }//GEN-LAST:event_agregarMunActionPerformed

    private void modificarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMunActionPerformed
        Municipio municipioSeleccionado = listaMunicipios.get(filaSeleccionadaMun);
        //Colocar el nuevo municipio modificado en la tabla y en el ArrayList.
        municipioSeleccionado.setCodDptoMun(códigoDepartamentoMun.getText().trim());
        municipioSeleccionado.setNombreMun(nombreMunicipio.getText().trim());
        //Actualizar los datos en la tabla.
        listadeMunicipios.setValueAt(códigoDepartamentoMun.getText().trim(), filaSeleccionadaMun, 0);
        listadeMunicipios.setValueAt(nombreMunicipio.getText().trim(), filaSeleccionadaMun, 1);
        JOptionPane.showMessageDialog(null, "Kiosco modificado correctamente", "Proceso exitoso", JOptionPane.INFORMATION_MESSAGE);
        //Limpiando los TextFields.
        códigoDepartamentoMun.setText("");
        nombreMunicipio.setText("");
    }//GEN-LAST:event_modificarMunActionPerformed

    private void eliminarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarMunActionPerformed

    private void editarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMunActionPerformed
        /*Si no hay ninguna fila seleccionada, mostrará un mensaje de error*/
        if (listadeMunicipios.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            /*Si alguna fila fue seleccionada, procede a enviar los datos de la fila a los TextFields
            para poder editarlos.*/
            filaSeleccionadaMun = listadeMunicipios.getSelectedRow();
            códigoDepartamentoMun.setText(listadeMunicipios.getValueAt(listadeMunicipios.getSelectedRow(), 0).toString());
            nombreMunicipio.setText(listadeMunicipios.getValueAt(listadeMunicipios.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_editarMunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Municipios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMun;
    private javax.swing.JTextField códigoDepartamentoMun;
    private javax.swing.JButton editarMun;
    private javax.swing.JButton eliminarMun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listadeMunicipios;
    private javax.swing.JButton modificarMun;
    private javax.swing.JTextField nombreMunicipio;
    private javax.swing.JButton regdepartamentos;
    // End of variables declaration//GEN-END:variables
}
