package Interfaz;

import static Interfaz.Autenticación.Mu;
import Lógica.Tarjeta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistroTarjetas extends javax.swing.JFrame {

    public static ArrayList<Tarjeta> listaTarjetas = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    private int filaSeleccionadaTarjetas;

    public RegistroTarjetas() {
        initComponents();
        model.addColumn("Nombre en la tarjeta");
        model.addColumn("Número de tarjeta");
        model.addColumn("Fecha de vencimiento");
        listadeTarjetas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listadeTarjetas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numTarjeta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaVencimiento = new javax.swing.JTextField();
        regMenúUsuario = new javax.swing.JButton();
        agregarTarjeta = new javax.swing.JButton();
        eliminarTarjeta = new javax.swing.JButton();
        editarTarjeta = new javax.swing.JButton();
        modificarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listadeTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listadeTarjetas);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE TARJETAS");

        jLabel2.setText("Nombre en la tarjeta:");

        jLabel3.setText("Número de la tarjeta:");

        numTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTarjetaActionPerformed(evt);
            }
        });
        numTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTarjetaKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha de vencimiento");

        fechaVencimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaVencimientoKeyTyped(evt);
            }
        });

        regMenúUsuario.setText("Regresar");
        regMenúUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMenúUsuarioActionPerformed(evt);
            }
        });

        agregarTarjeta.setText("Agregar");
        agregarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTarjetaActionPerformed(evt);
            }
        });

        eliminarTarjeta.setText("Eliminar");
        eliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTarjetaActionPerformed(evt);
            }
        });

        editarTarjeta.setText("Editar");
        editarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTarjetaActionPerformed(evt);
            }
        });

        modificarTarjeta.setText("Modificar");
        modificarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regMenúUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(eliminarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(agregarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(editarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(modificarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(nombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regMenúUsuario)
                    .addComponent(eliminarTarjeta)
                    .addComponent(agregarTarjeta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarTarjeta)
                    .addComponent(modificarTarjeta))
                .addGap(62, 71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTarjetaActionPerformed
        if (nombreTarjeta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar el nombre del propietario de la tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (numTarjeta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar el número de la tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (!numTarjeta.getText().matches(".*[0-9].*") || numTarjeta.getText().matches(".*[A-Z].*") || numTarjeta.getText().matches(".*[a-z].*")) {
            JOptionPane.showMessageDialog(this, "Solo debe ingresar números", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (fechaVencimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar la fecha de vencimiento", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        Tarjeta tar = new Tarjeta(nombreTarjeta.getText(), numTarjeta.getText(), fechaVencimiento.getText());
        listaTarjetas.add(tar);
        String numTarjetaCompleto = numTarjeta.getText();
        String numTarjetaOculto = "**************" + numTarjetaCompleto.substring(14);
        model.addRow(new Object[]{nombreTarjeta.getText(), numTarjetaOculto, fechaVencimiento.getText()});
        listadeTarjetas.setModel(model);
        JOptionPane.showMessageDialog(this, "Tarjeta agregada correctamente", "Proceso Exitoso", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(true);
        nombreTarjeta.setText("");
        numTarjeta.setText("");
        fechaVencimiento.setText("");
    }//GEN-LAST:event_agregarTarjetaActionPerformed

    private void regMenúUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMenúUsuarioActionPerformed
        this.setVisible(false);
        if (Mu == null) {
            Mu = new MenúUsuario();
        }
        Mu.setVisible(true);
        Mu.setLocationRelativeTo(null);
    }//GEN-LAST:event_regMenúUsuarioActionPerformed

    private void editarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTarjetaActionPerformed
        //Verificando si alguna fila no fue seleccionada.
        if (listadeTarjetas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            /*Si alguna fila fue seleccionada, procede a enviar los datos de la fila a los TextFields
            para poder editarlos.*/
            filaSeleccionadaTarjetas = listadeTarjetas.getSelectedRow();
            nombreTarjeta.setText(listadeTarjetas.getValueAt(listadeTarjetas.getSelectedRow(), 0).toString());
            numTarjeta.setText(listadeTarjetas.getValueAt(listadeTarjetas.getSelectedRow(), 1).toString());
            fechaVencimiento.setText(listadeTarjetas.getValueAt(listadeTarjetas.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_editarTarjetaActionPerformed

    private void modificarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTarjetaActionPerformed
        if (nombreTarjeta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar el nombre del propietario de la tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (numTarjeta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar el número de la tarjeta", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        if (fechaVencimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe agregar la fecha de vencimiento", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            return;
        }
        Tarjeta tarjetaSeleccionada = listaTarjetas.get(filaSeleccionadaTarjetas);
        //Colocar la nuevz tarjeta en la tabla y en el ArrayList.
        tarjetaSeleccionada.setNombredeTarjeta(nombreTarjeta.getText().trim());
        tarjetaSeleccionada.setNúmerodeTarjeta(numTarjeta.getText().trim());
        tarjetaSeleccionada.setFechadeVencimiento(fechaVencimiento.getText().trim());
        //Actualizar los datos en la tabla.
        String numTarjetaCompleto = numTarjeta.getText();
        String numTarjetaOculto = "**************" + numTarjetaCompleto.substring(14);
        listadeTarjetas.setValueAt(nombreTarjeta.getText().trim(), filaSeleccionadaTarjetas, 0);
        listadeTarjetas.setValueAt(numTarjetaOculto, filaSeleccionadaTarjetas, 1);
        listadeTarjetas.setValueAt(fechaVencimiento.getText().trim(), filaSeleccionadaTarjetas, 2);
        JOptionPane.showMessageDialog(null, "Tarjeta modificada correctamente", "Proceso exitoso", JOptionPane.INFORMATION_MESSAGE);
        //Limpiando los TextFields.
        nombreTarjeta.setText("");
        numTarjeta.setText("");
        fechaVencimiento.setText("");
    }//GEN-LAST:event_modificarTarjetaActionPerformed

    private void eliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTarjetaActionPerformed
        int selectedRow = listadeTarjetas.getSelectedRow();
        //Validando que la fila si haya sido seleccionado.
        if (selectedRow != -1) {
            //Obteniendo el objeto correspondiente al Arraylist dependiendo de la fila seleccionada.
            Tarjeta Tjt = listaTarjetas.get(selectedRow);

            //Método para eliminar la fila seleccionada.
            listaTarjetas.remove(Tjt);

            //Actualizando la tabla sin el objeto que se eliminó previamente.
            DefaultTableModel modelo = (DefaultTableModel) listadeTarjetas.getModel();
            model.removeRow(selectedRow);

            JOptionPane.showMessageDialog(null, "Tarjeta eliminada", "Proceso Exitoso", JOptionPane.INFORMATION_MESSAGE);
            //Vaciando de nuevo los TextFields.
            nombreTarjeta.setText("");
            numTarjeta.setText("");
            fechaVencimiento.setText("");
        } else { //Si no se seleccionó ninguna fila mostrará un JOptionPane con el error.
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarTarjetaActionPerformed

    private void numTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTarjetaActionPerformed

    }//GEN-LAST:event_numTarjetaActionPerformed

    private void numTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTarjetaKeyTyped
        if (numTarjeta.getText().length() >= 19) {
            evt.consume();
        }
    }//GEN-LAST:event_numTarjetaKeyTyped

    private void fechaVencimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaVencimientoKeyTyped
        if (fechaVencimiento.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_fechaVencimientoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroTarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTarjeta;
    private javax.swing.JButton editarTarjeta;
    private javax.swing.JButton eliminarTarjeta;
    private javax.swing.JTextField fechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listadeTarjetas;
    private javax.swing.JButton modificarTarjeta;
    private javax.swing.JTextField nombreTarjeta;
    private javax.swing.JTextField numTarjeta;
    private javax.swing.JButton regMenúUsuario;
    // End of variables declaration//GEN-END:variables
}
